/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import sun.misc.BASE64Encoder;

/**
 *
 * @author pasindu
 */
public class NewUser extends javax.swing.JFrame {

    private static Point point = new Point();
    String encoded;
    String p1;
    String decoded;
    int i = 0;

    /**
     * Creates new form NewUser
     */
    public NewUser() {
        initComponents();
        setLocationRelativeTo(null);
        setIconImage(Toolkit.getDefaultToolkit().getImage("Reports/logo.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtxusername = new javax.swing.JTextField();
        Name = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtoccupation = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cbut = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtx = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtxxx = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cb2 = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txtpassword = new javax.swing.JPasswordField();
        txtconfiirmpasswoord = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtpic = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        txtpath = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        lbpic = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        Name1 = new javax.swing.JLabel();
        txtname1 = new javax.swing.JTextField();
        txtpath1 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jButton10 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setBackground(new java.awt.Color(51, 51, 51));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/close_box_red.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 0, 30, 30));

        jButton8.setBackground(new java.awt.Color(51, 51, 51));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/window_2.png"))); // NOI18N
        jPanel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 30, 30));

        jButton5.setBackground(new java.awt.Color(51, 51, 51));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/minimize_box_blue.png"))); // NOI18N
        jButton5.setBorderPainted(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 30, 30));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 21)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 51));
        jLabel3.setText("Student Information System");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 450, -1));

        jLabel12.setFont(new java.awt.Font("Old English Text MT", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 0));
        jLabel12.setText("D.S. Senanayake College  - Science Section");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 300, 20));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/logo.png"))); // NOI18N
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 50, 60));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel25.setText("Edit User Account");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 320, 20));

        jLabel26.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel26.setText("Create New User Account");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 320, 20));
        jPanel3.add(txtxusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 240, -1));

        Name.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Name.setText("Name");
        jPanel3.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 70, 20));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setText("Password");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 70, 20));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel6.setText("Confirm Password");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 110, 20));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel7.setText("User Type");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 110, 20));
        jPanel3.add(txtoccupation, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 240, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel8.setText("Occupation");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 110, 20));

        cbut.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrater", "User" }));
        jPanel3.add(cbut, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, -1));

        jButton1.setText("Create New User");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 300, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setText("User Name");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 70, 20));

        txtx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtxKeyPressed(evt);
            }
        });
        jPanel3.add(txtx, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 140, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel9.setText("Occupation");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 110, 20));
        jPanel3.add(txtxxx, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 240, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel10.setText("User Type");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 110, 20));

        cb2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrater", "User" }));
        jPanel3.add(cb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, -1, -1));

        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 90, -1));

        jButton4.setText("Update User Account");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, 170, -1));
        jPanel3.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 240, -1));
        jPanel3.add(txtconfiirmpasswoord, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 240, -1));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel14.setText("Account Picture");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 100, 20));
        jPanel3.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 240, -1));

        txtpic.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(txtpic, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, 120, 150));

        jButton2.setText("Choose");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 100, -1, -1));
        jPanel3.add(txtpath, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 210, -1));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel15.setText("User Name");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 70, 20));

        lbpic.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(lbpic, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 120, 150));

        jButton7.setText("Change Account Picture");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 520, -1, -1));

        Name1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Name1.setText("Name");
        jPanel3.add(Name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 70, 20));
        jPanel3.add(txtname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 240, -1));
        jPanel3.add(txtpath1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 560, 260, -1));

        jButton9.setText("Cancel");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 520, 90, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 730, 20));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 730, 20));

        jButton10.setText("Change Password");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 550, 150, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel30.setText("© 2012  Cape Weaver Solutions. All rights reserved.");
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, -1, 20));

        jButton11.setText("Delete User Account");
        jButton11.setMaximumSize(new java.awt.Dimension(135, 23));
        jButton11.setMinimumSize(new java.awt.Dimension(135, 23));
        jButton11.setPreferredSize(new java.awt.Dimension(135, 23));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, 170, 23));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Backgrond.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 640));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 770, 640));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Object[] options = {"Yes", "No"};
        int n = JOptionPane.showOptionDialog(new JFrame(), "Are you sure?", "Student Information System ", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[1]);
        if (n == JOptionPane.OK_OPTION) { // Afirmative
            Login.mainFrame.setVisible(true);
            setnull();
            dispose();
            System.out.println("ok");
        }
        if (n == JOptionPane.NO_OPTION) { // negative
            System.out.println("no");
        }
        if (n == JOptionPane.CLOSED_OPTION) { // closed the dialog
            System.out.println("close");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        setState(ICONIFIED);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            File image = new File(txtpath.getText().replace("\\", "/"));
            FileInputStream fis = new FileInputStream(image);
            Connection connection = DataBase.Createconnection();
            PreparedStatement statement = null;
            System.out.println("ela");
            if (txtpassword.getText().equals(txtconfiirmpasswoord.getText())) {
                p1 = txtpassword.getText();
                encoded = (new BASE64Encoder()).encode(p1.getBytes("UTF-8"));
                DataBase.executeupdate("Insert into login(username,name,password,occupation,usertype) values('" + txtxusername.getText() + "','" + txtname.getText() + "','" + encoded + "','" + txtoccupation.getText() + "','" + cbut.getSelectedItem() + "')");
                System.out.println("del");
                statement = connection.prepareStatement("Update login  set picture=? where username ='" + txtxusername.getText() + "'");
                System.out.println("pol");
                statement.setBinaryStream(1, (InputStream) fis, (int) (image.length()));
                System.out.println(image.length());
                statement.executeUpdate();
                System.out.println("elama kiri");

            }
            connection = null;
            setnull();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtxKeyPressed

        if (evt.getKeyCode() == 10) {

            search();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtxKeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        search();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            File image = new File(txtpath1.getText().replace("\\", "/"));
            FileInputStream fis = new FileInputStream(image);
            Connection connection = DataBase.Createconnection();
            PreparedStatement statement = null;
            System.out.println("ela");
            if (txtpassword.getText().equals(txtconfiirmpasswoord.getText())) {
                p1 = txtpassword.getText();
                encoded = (new BASE64Encoder()).encode(p1.getBytes("UTF-8"));
                DataBase.executeupdate("update login set name='" + txtname1.getText() + "',occupation='" + txtxxx.getText() + "',usertype='" + cb2.getSelectedItem() + "'where username='" + txtx.getText() + "'");
                System.out.println("del");
                if (txtpath1.getText() != "") {
                    statement = connection.prepareStatement("Update login  set picture=? where username ='" + txtx.getText() + "'");
                    System.out.println("pol");
                    statement.setBinaryStream(1, (InputStream) fis, (int) (image.length()));
                    System.out.println(image.length());
                    statement.executeUpdate();
                    System.out.println("elama kiri");
                }
            }
            connection = null;
            setnull();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            txtpath.setText(getBackUpPath());
            String newpath = txtpath.getText().replace("\\", "/");
            System.out.println(newpath);

            File ff = new File(newpath);
            Image img = ImageIO.read(ff);
            img = img.getScaledInstance(lbpic.getWidth(), lbpic.getHeight(), Image.SCALE_SMOOTH);
            lbpic.setIcon(new ImageIcon(img));
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {
            txtpath1.setText(getBackUpPath());
            String newpath = txtpath1.getText().replace("\\", "/");
            System.out.println(newpath);

            File ff = new File(newpath);
            Image img = ImageIO.read(ff);
            img = img.getScaledInstance(txtpic.getWidth(), txtpic.getHeight(), Image.SCALE_SMOOTH);
            txtpic.setIcon(new ImageIcon(img));
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        try {

            Blob imageBlob = null;
            Image image;
            ResultSet rs = DataBase.executequary1("login", "username", txtx.getText());
            if (rs.next()) {

                imageBlob = rs.getBlob("picture");
                InputStream binaryStream = imageBlob.getBinaryStream(1, imageBlob.length());
                System.out.println("elakiri");
                image = ImageIO.read(binaryStream);
                image = image.getScaledInstance(txtpic.getWidth(), txtpic.getHeight(), Image.SCALE_SMOOTH);
                txtpic.setIcon(new ImageIcon(image));
                txtpath1.setText("");
            }

            // TODO add your handling code here:
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        Point p = getLocation();
        setLocation(p.x + evt.getX() - point.x, p.y + evt.getY() - point.y);// TODO add your handling code here:
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        point.x = evt.getX();
        point.y = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        MainFrame.changePassword.setVisible(true);
        ChangePassword.b2 = 2;
        ChangePassword.username(txtx.getText(), Login.username);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        try {
            MainFrame.deleteAccount.setVisible(true);
            DeleteAccount.username(txtx.getText());
            

        } catch (Exception e) {
            e.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewUser().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Name1;
    private javax.swing.JComboBox cb2;
    private javax.swing.JComboBox cbut;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbpic;
    private javax.swing.JPasswordField txtconfiirmpasswoord;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtname1;
    private javax.swing.JTextField txtoccupation;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtpath;
    private javax.swing.JTextField txtpath1;
    private javax.swing.JLabel txtpic;
    private javax.swing.JTextField txtx;
    private javax.swing.JTextField txtxusername;
    private javax.swing.JTextField txtxxx;
    // End of variables declaration//GEN-END:variables

    public static String getBackUpPath() {

        String backUpPath = "";
        JFileChooser fc = null;
        if (fc == null) {
            fc = new JFileChooser();
            fc.setFileSelectionMode(JFileChooser.FILES_ONLY);

            fc.setAcceptAllFileFilterUsed(true);
            ImagePriview preview = new ImagePriview();
            fc.setAccessory(preview);
            fc.addPropertyChangeListener(preview);

        }
        int returnVal = fc.showDialog(null, "Open");
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();

            backUpPath = file.getAbsolutePath();

        }
        return backUpPath;

    }

    public void search() {
        try {
            Blob imageBlob = null;
            Image image;
            ResultSet rs = DataBase.executequary1("login", "username", txtx.getText());
            while (rs.next()) {
                txtxxx.setText(rs.getString("occupation"));
                cb2.setSelectedItem(rs.getString("usertype"));
                txtname1.setText(rs.getString("name"));
                imageBlob = rs.getBlob("picture");

            }

            InputStream binaryStream = imageBlob.getBinaryStream(1, imageBlob.length());
            System.out.println("elakiri");
            image = ImageIO.read(binaryStream);
            image = image.getScaledInstance(txtpic.getWidth(), txtpic.getHeight(), Image.SCALE_SMOOTH);
            txtpic.setIcon(new ImageIcon(image));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void setnull() {
        lbpic.setIcon(null);
        txtconfiirmpasswoord.setText("");
        txtname.setText("");
        txtname1.setText("");
        txtoccupation.setText("");
        txtpassword.setText("");
        txtpath.setText("");
        txtpath1.setText("");
        txtpic.setText("");
        txtx.setText("");
        txtxusername.setText("");
        txtxxx.setText("");

    }
}
