/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Locale;
import java.util.Vector;
import javax.imageio.ImageIO;
import javax.swing.*;

/**
 *
 * @author pasindu
 */
public class SearchStudent extends javax.swing.JFrame {

    static String stsubject = "Maths";
    static String ndsubject = "Physics";
    private static Point point = new Point();

    /**
     * Creates new form AddStudent
     */
    public SearchStudent() {
        initComponents();
        setLocationRelativeTo(null);
        txt_admission_no.requestFocus();
        jSeparator1.setForeground(Color.black);
        setIconImage(Toolkit.getDefaultToolkit().getImage("Reports/logo.png"));






    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        lbl_photo = new javax.swing.JLabel();
        txt_admission_no = new javax.swing.JTextField();
        txt_full_name = new javax.swing.JTextField();
        txt_name_initials = new javax.swing.JTextField();
        txt_nic = new javax.swing.JTextField();
        txt_fatehes_name = new javax.swing.JTextField();
        txt_fathers_occupation = new javax.swing.JTextField();
        txt_fathers_contactno = new javax.swing.JTextField();
        txt_mothers_name = new javax.swing.JTextField();
        txt_mothers_occ = new javax.swing.JTextField();
        txt_mothers_contactno = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_special_notes = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_address = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_ex_curricular = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        txt_mothers_officeadd = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        txt_fathers_officeaddress = new javax.swing.JTextPane();
        dc_admission_date = new com.toedter.calendar.JDateChooser();
        cb_admission_grade = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        dc_examyear = new com.toedter.calendar.JYearChooser();
        cb_3rd_subject = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        cb_regno = new javax.swing.JComboBox();
        dc_birthday = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        txtpath = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        cb_grade = new javax.swing.JComboBox();
        cb_class = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setText("Search Student");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Occupation");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Grade");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Father's Name");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 230, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Exam Year");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Contact No");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 340, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel11.setText("Parential Perticulars");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Office Address");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 290, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Extra Curricular Activities");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("NIC No");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("Special Notes");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("3rd Subject");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("Admission Grade");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setText("Admission No");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setText("Name with initials");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setText("Admission Date");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setText("Address");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setText("Birth Day");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setText("Full Name");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel25.setText("Mother's Name");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 440, -1, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel26.setText("Occupation");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 470, -1, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel27.setText("Office Address");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 500, -1, -1));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel28.setText("Contact No");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 550, -1, -1));

        lbl_photo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_photo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_photo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(lbl_photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 40, 110, 140));
        jPanel1.add(txt_admission_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 210, -1));
        jPanel1.add(txt_full_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 210, -1));
        jPanel1.add(txt_name_initials, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 210, -1));
        jPanel1.add(txt_nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 210, -1));
        jPanel1.add(txt_fatehes_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 230, 210, -1));
        jPanel1.add(txt_fathers_occupation, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 260, 210, -1));
        jPanel1.add(txt_fathers_contactno, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 340, 210, -1));
        jPanel1.add(txt_mothers_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 440, 210, -1));
        jPanel1.add(txt_mothers_occ, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 470, 210, -1));
        jPanel1.add(txt_mothers_contactno, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 550, 210, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 1080, 10));

        jScrollPane1.setViewportView(txt_special_notes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 540, 290, 80));

        jScrollPane2.setViewportView(txt_address);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 280, 60));

        jScrollPane3.setViewportView(txt_ex_curricular);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 290, 80));

        jScrollPane4.setViewportView(txt_mothers_officeadd);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 500, 210, 40));

        jScrollPane5.setViewportView(txt_fathers_officeaddress);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 290, 210, 40));

        dc_admission_date.setDateFormatString("dd-MM-yyyy");
        jPanel1.add(dc_admission_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 210, -1));

        cb_admission_grade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13" }));
        jPanel1.add(cb_admission_grade, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel7.setText("Reg. No");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, -1, -1));
        jPanel1.add(dc_examyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 60, -1));

        cb_3rd_subject.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Chemistry", "IT", "Agriculture" }));
        cb_3rd_subject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_3rd_subjectActionPerformed(evt);
            }
        });
        jPanel1.add(cb_3rd_subject, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, -1, -1));

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 600, -1, -1));

        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 600, -1, -1));

        jButton4.setText("Discard");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 600, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Class");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, -1));

        cb_regno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cb_regno.setSelectedIndex(-1);
        cb_regno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_regnoActionPerformed(evt);
            }
        });
        jPanel1.add(cb_regno, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, -1, -1));

        dc_birthday.setDateFormatString("dd-MM-yyyy");
        jPanel1.add(dc_birthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 210, -1));

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 80, -1));

        jButton9.setText("Search");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 230, 80, -1));

        jButton10.setText("Search");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 440, 80, -1));

        jButton11.setText("Search");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 80, -1));
        jPanel1.add(txtpath, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, 250, -1));

        jButton13.setText("Choose");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 150, -1, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel30.setText("© 2012  Cape Weaver Solutions. All rights reserved.");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 620, -1, 20));

        jButton12.setText("Delete");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 600, -1, -1));

        jButton14.setText("Search");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 90, -1));

        cb_grade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "12", "13", "14" }));
        cb_grade.setSelectedIndex(-1);
        cb_grade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_gradeActionPerformed(evt);
            }
        });
        jPanel1.add(cb_grade, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, -1, -1));

        cb_class.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_classActionPerformed(evt);
            }
        });
        jPanel1.add(cb_class, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Backgrond.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 640));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 1120, 640));

        jButton6.setBackground(new java.awt.Color(51, 51, 51));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/close_box_red.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 0, 30, 30));

        jButton8.setBackground(new java.awt.Color(51, 51, 51));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/window_2.png"))); // NOI18N
        jPanel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 0, 30, 30));

        jButton5.setBackground(new java.awt.Color(51, 51, 51));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/minimize_box_blue.png"))); // NOI18N
        jButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.setBorderPainted(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 0, 30, 30));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 21)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 51));
        jLabel3.setText("Student Information System");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 450, -1));

        jLabel12.setFont(new java.awt.Font("Old English Text MT", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 0));
        jLabel12.setText("D.S. Senanayake College  - Science Section");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 300, 20));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/logo.png"))); // NOI18N
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 50, 60));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
             DataBase.executeupdate("UPDATE  student set regno='" + cb_regno.getSelectedItem() + "',fullname='" + txt_full_name.getText() + "',namewithinitials='" + txt_name_initials.getText() + "',address='" + txt_address.getText() + "',birthday='" + String.format("%1$tY-%1$tm-%1$td", dc_birthday.getDate()) + "',admissiongrade='" + cb_admission_grade.getSelectedItem() + "',admissiondate='" + String.format("%1$tY-%1$tm-%1$td", dc_admission_date.getDate()) + "',class='" + cb_class.getSelectedItem() + "',nic='" + txt_nic.getText() + "',year='" + dc_examyear.getYear() + "',1subject='" + stsubject + "',2subject='" + ndsubject + "',3subject='" + cb_3rd_subject.getSelectedItem() + "',specialnotes='" + txt_special_notes.getText() + "',excuricularact='" + txt_ex_curricular.getText() + "',statues='" + 1 + "' where admissionno='" + txt_admission_no.getText() + "'");
            
            if (txtpath.getText().equals("")) {
                
            } else {
          
            File image = new File(txtpath.getText().replace("\\", "/"));
            FileInputStream fis = new FileInputStream(image);
            Connection connection = DataBase.Createconnection();
            PreparedStatement statement = null;
            System.out.println("ela");


            DataBase.executeupdate("UPDATE  student set regno='" + cb_regno.getSelectedItem() + "',fullname='" + txt_full_name.getText() + "',namewithinitials='" + txt_name_initials.getText() + "',address='" + txt_address.getText() + "',birthday='" + String.format("%1$tY-%1$tm-%1$td", dc_birthday.getDate()) + "',admissiongrade='" + cb_admission_grade.getSelectedItem() + "',admissiondate='" + String.format("%1$tY-%1$tm-%1$td", dc_admission_date.getDate()) + "',class='" + cb_class.getSelectedItem() + "',nic='" + txt_nic.getText() + "',year='" + dc_examyear.getYear() + "',1subject='" + stsubject + "',2subject='" + ndsubject + "',3subject='" + cb_3rd_subject.getSelectedItem() + "',specialnotes='" + txt_special_notes.getText() + "',excuricularact='" + txt_ex_curricular.getText() + "',statues='" + 1 + "' where admissionno='" + txt_admission_no.getText() + "'");
            System.out.println("del");
            statement = connection.prepareStatement("Update student  set photo=? where admissionno ='" + txt_admission_no.getText() + "'");
            System.out.println("pol");
            statement.setBinaryStream(1, (InputStream) fis, (int) (image.length()));
            System.out.println(image.length());
            statement.executeUpdate();
            System.out.println("elama kiri");
            connection = null;
            }
            DataBase.executeupdate("UPDATE father SET name='" + txt_fatehes_name.getText() + "',occupation='" + txt_fathers_occupation.getText() + "',officeaddress='" + txt_fathers_officeaddress.getText() + "',contactno='" + txt_fathers_contactno.getText() + "'where admissionno='" + txt_admission_no.getText() + "' ");
            DataBase.executeupdate("UPDATE mother set name='" + txt_mothers_name.getText() + "',occupation='" + txt_mothers_occ.getText() + "',officeaddress='" + txt_mothers_officeadd.getText() + "',contactno='" + txt_mothers_contactno.getText() + "' where admissionno='" + txt_admission_no.getText() + "'");

            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Object[] options = {"Yes", "No"};
        int n = JOptionPane.showOptionDialog(new JFrame(), "Are you sure?", "Student Information System ", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[1]);
        if (n == JOptionPane.OK_OPTION) { // Afirmative
            Login.mainFrame.setVisible(true);
            Setnull();
            txt_admission_no.setText("");
            txt_mothers_name.setText("");
            txt_fatehes_name.setText("");
            cb_grade.setSelectedIndex(-1);
            cb_class.setSelectedIndex(-1);
            cb_regno.setSelectedIndex(-1);
            dispose();
            System.out.println("ok");
        }
        if (n == JOptionPane.NO_OPTION) { // negative
            System.out.println("no");
        }
        if (n == JOptionPane.CLOSED_OPTION) { // closed the dialog
            System.out.println("close");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Object[] options = {"Yes", "No"};
        int n = JOptionPane.showOptionDialog(new JFrame(), "Are you sure?", "Student Information System ", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[1]);
        if (n == JOptionPane.OK_OPTION) { // Afirmative
            Login.mainFrame.setVisible(true);
            Setnull();
            txt_admission_no.setText("");
            txt_mothers_name.setText("");
            txt_fatehes_name.setText("");
            cb_grade.setSelectedIndex(-1);
            cb_class.setSelectedIndex(-1);
            cb_regno.setSelectedIndex(-1);
            dispose();
            System.out.println("ok");
        }
        if (n == JOptionPane.NO_OPTION) { // negative
            System.out.println("no");
        }
        if (n == JOptionPane.CLOSED_OPTION) { // closed the dialog
            System.out.println("close");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        setState(ICONIFIED);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        point.x = evt.getX();
        point.y = evt.getY();        // TODO add your handling code here:
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        Point p = getLocation();
        setLocation(p.x + evt.getX() - point.x, p.y + evt.getY() - point.y);        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseDragged

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Setnull();
        txt_admission_no.setText("");
        txt_mothers_name.setText("");
        txt_fatehes_name.setText("");
        cb_grade.setSelectedIndex(-1);
        cb_class.setSelectedIndex(-1);
        cb_regno.setSelectedIndex(-1);




    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        try {
            Setnull();
            Blob imageBlob = null;
            Image image = null;
            ResultSet rs1 = DataBase.executequary1("student", "admissionno", txt_admission_no.getText());
            if (rs1.next()) {
                ResultSet rs = DataBase.executequary1("student", "admissionno", txt_admission_no.getText());
                while (rs.next()) {
                    txt_full_name.setText(rs.getString("fullname"));
                    txt_name_initials.setText(rs.getString("namewithinitials"));
                    txt_address.setText(rs.getString("address"));
                    dc_birthday.setDate(new SimpleDateFormat("yyyy-MM-dd", Locale.ENGLISH).parse(rs.getString("birthday")));
                    cb_admission_grade.setSelectedItem(rs.getString("admissiongrade"));
                    dc_admission_date.setDate(new SimpleDateFormat("yyyy-MM-dd", Locale.ENGLISH).parse(rs.getString("admissiondate")));
                    txt_nic.setText(rs.getString("nic"));
                    String a[] = rs.getString("class").split("_");
                    cb_grade.setSelectedItem(a[0]);
                    cb_class.setSelectedItem(rs.getString("class"));
                    dc_examyear.setYear(Integer.parseInt(rs.getString("year")));

                    cb_3rd_subject.setSelectedItem(rs.getString("3subject"));
                    txt_ex_curricular.setText(rs.getString("excuricularact"));
                    txt_special_notes.setText(rs.getString("specialnotes"));
                    imageBlob = rs.getBlob("photo");
                    InputStream binaryStream = imageBlob.getBinaryStream(1, imageBlob.length());
                    System.out.println("elakiri");
                    image = ImageIO.read(binaryStream);
                    image = image.getScaledInstance(lbl_photo.getWidth(), lbl_photo.getHeight(), Image.SCALE_SMOOTH);
                    cb_regno.setSelectedItem(rs.getString("regno"));

                }

                lbl_photo.setIcon(new ImageIcon(image));
                ResultSet rs2 = DataBase.executequary1("father", "admissionno", txt_admission_no.getText());
                while (rs2.next()) {
                    txt_fatehes_name.setText(rs2.getString("name"));
                    txt_fathers_occupation.setText(rs2.getString("occupation"));
                    txt_fathers_officeaddress.setText(rs2.getString("officeaddress"));
                    txt_fathers_contactno.setText(rs2.getString("contactno"));
                }
                ResultSet rs3 = DataBase.executequary1("mother", "admissionno", txt_admission_no.getText());
                while (rs3.next()) {
                    txt_mothers_name.setText(rs3.getString("name"));
                    txt_mothers_occ.setText(rs3.getString("occupation"));
                    txt_mothers_officeadd.setText(rs3.getString("officeaddress"));
                    txt_mothers_contactno.setText(rs3.getString("contactno"));
                }
            } else {
                Object[] options = {"Ok"};
                JOptionPane.showOptionDialog(new JFrame(), "Wrong Admission Number", "Student Information System", JOptionPane.OK_OPTION, JOptionPane.ERROR_MESSAGE, null, options, options[0]);
                txt_admission_no.setText("");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        try {
            txtpath.setText(getBackUpPath());
            String newpath = txtpath.getText().replace("\\", "/");
            System.out.println(newpath);

            File ff = new File(newpath);
            Image img = ImageIO.read(ff);
            img = img.getScaledInstance(lbl_photo.getWidth(), lbl_photo.getHeight(), Image.SCALE_SMOOTH);
            lbl_photo.setIcon(new ImageIcon(img));
        } catch (IOException ex) {
            ex.printStackTrace();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Setnull();
            Blob imageBlob = null;
            Image image = null;
            ResultSet rs1 = DataBase.executequary1("student", "namewithinitials", txt_name_initials.getText());
            if (rs1.next()) {
                ResultSet rs = DataBase.executequary1("student", "namewithinitials", txt_name_initials.getText());
                while (rs.next()) {
                    txt_admission_no.setText(rs.getString("admissionno"));
                    txt_full_name.setText(rs.getString("fullname"));
                    txt_name_initials.setText(rs.getString("namewithinitials"));
                    txt_address.setText(rs.getString("address"));
                    dc_birthday.setDate(new SimpleDateFormat("yyyy-MM-dd", Locale.ENGLISH).parse(rs.getString("birthday")));
                    cb_admission_grade.setSelectedItem(rs.getString("admissiongrade"));
                    dc_admission_date.setDate(new SimpleDateFormat("yyyy-MM-dd", Locale.ENGLISH).parse(rs.getString("admissiondate")));
                    txt_nic.setText(rs.getString("nic"));
                    String a[] = rs.getString("class").split("_");
                    cb_grade.setSelectedItem(a[0]);
                    cb_class.setSelectedItem(rs.getString("class"));
                    dc_examyear.setYear(Integer.parseInt(rs.getString("year")));
                    cb_regno.setSelectedItem(rs.getString("regno"));
                    cb_3rd_subject.setSelectedItem(rs.getString("3subject"));
                    txt_ex_curricular.setText(rs.getString("excuricularact"));
                    txt_special_notes.setText(rs.getString("specialnotes"));
                    imageBlob = rs.getBlob("photo");
                    InputStream binaryStream = imageBlob.getBinaryStream(1, imageBlob.length());
                    System.out.println("elakiri");
                    image = ImageIO.read(binaryStream);
                    image = image.getScaledInstance(lbl_photo.getWidth(), lbl_photo.getHeight(), Image.SCALE_SMOOTH);

                }
                lbl_photo.setIcon(new ImageIcon(image));
                ResultSet rs2 = DataBase.executequary1("father", "admissionno", txt_admission_no.getText());
                while (rs2.next()) {
                    txt_fatehes_name.setText(rs2.getString("name"));
                    txt_fathers_occupation.setText(rs2.getString("occupation"));
                    txt_fathers_officeaddress.setText(rs2.getString("officeaddress"));
                    txt_fathers_contactno.setText(rs2.getString("contactno"));
                }
                ResultSet rs3 = DataBase.executequary1("mother", "admissionno", txt_admission_no.getText());
                while (rs3.next()) {
                    txt_mothers_name.setText(rs3.getString("name"));
                    txt_mothers_occ.setText(rs3.getString("occupation"));
                    txt_mothers_officeadd.setText(rs3.getString("officeaddress"));
                    txt_mothers_contactno.setText(rs3.getString("contactno"));
                }
            } else {
                Object[] options = {"Ok"};
                JOptionPane.showOptionDialog(new JFrame(), "Name doesn't exsist please check spelling and try again", "Student Information System", JOptionPane.OK_OPTION, JOptionPane.ERROR_MESSAGE, null, options, options[0]);
                txt_name_initials.setText("");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
try {
            Setnull();
            ResultSet rs1 = DataBase.executequary1("father", "name", txt_fatehes_name.getText());
            if (rs1.next()) {
                ResultSet rs2 = DataBase.executequary1("father", "name", txt_fatehes_name.getText());
                while (rs2.next()) {
                    txt_admission_no.setText(rs2.getString("admissionno"));
                    txt_fathers_occupation.setText(rs2.getString("occupation"));
                    txt_fathers_officeaddress.setText(rs2.getString("officeaddress"));
                    txt_fathers_contactno.setText(rs2.getString("contactno"));
                }
                Blob imageBlob = null;
                Image image = null;


                ResultSet rs = DataBase.executequary1("student", "admissionno", txt_admission_no.getText());
                while (rs.next()) {
                    txt_admission_no.setText(rs.getString("admissionno"));
                    txt_full_name.setText(rs.getString("fullname"));
                    txt_name_initials.setText(rs.getString("namewithinitials"));
                    txt_address.setText(rs.getString("address"));
                    dc_birthday.setDate(new SimpleDateFormat("yyyy-MM-dd", Locale.ENGLISH).parse(rs.getString("birthday")));
                    cb_admission_grade.setSelectedItem(rs.getString("admissiongrade"));
                    dc_admission_date.setDate(new SimpleDateFormat("yyyy-MM-dd", Locale.ENGLISH).parse(rs.getString("admissiondate")));
                    txt_nic.setText(rs.getString("nic"));
                    String a[] = rs.getString("class").split("_");
                    cb_grade.setSelectedItem(a[0]);
                    cb_class.setSelectedItem(rs.getString("class"));
                    dc_examyear.setYear(Integer.parseInt(rs.getString("year")));
                    cb_regno.setSelectedItem(rs.getString("regno"));
                    cb_3rd_subject.setSelectedItem(rs.getString("3subject"));
                    txt_ex_curricular.setText(rs.getString("excuricularact"));
                    txt_special_notes.setText(rs.getString("specialnotes"));
                    imageBlob = rs.getBlob("photo");
                    InputStream binaryStream = imageBlob.getBinaryStream(1, imageBlob.length());
                    System.out.println("elakiri");
                    image = ImageIO.read(binaryStream);
                    image = image.getScaledInstance(lbl_photo.getWidth(), lbl_photo.getHeight(), Image.SCALE_SMOOTH);

                }
                lbl_photo.setIcon(new ImageIcon(image));
                ResultSet rs3 = DataBase.executequary1("mother", "admissionno", txt_admission_no.getText());
                while (rs3.next()) {
                    txt_mothers_name.setText(rs3.getString("name"));
                    txt_mothers_occ.setText(rs3.getString("occupation"));
                    txt_mothers_officeadd.setText(rs3.getString("officeaddress"));
                    txt_mothers_contactno.setText(rs3.getString("contactno"));
                }
            } else {
                Object[] options = {"Ok"};
                JOptionPane.showOptionDialog(new JFrame(), "Name doesn't exsist plase check spelling and try again", "Student Information System", JOptionPane.OK_OPTION, JOptionPane.ERROR_MESSAGE, null, options, options[0]);
                txt_fatehes_name.setText("");


            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }         
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        try {
            Setnull();
            ResultSet rs1 = DataBase.executequary1("mother", "name", txt_mothers_name.getText());
            if (rs1.next()) {
                ResultSet rs3 = DataBase.executequary1("mother", "name", txt_mothers_name.getText());
                while (rs3.next()) {
                    txt_admission_no.setText(rs3.getString("admissionno"));
                    txt_mothers_occ.setText(rs3.getString("occupation"));
                    txt_mothers_officeadd.setText(rs3.getString("officeaddress"));
                    txt_mothers_contactno.setText(rs3.getString("contactno"));
                }
                Blob imageBlob = null;
                Image image = null;


                ResultSet rs = DataBase.executequary1("student", "admissionno", txt_admission_no.getText());
                while (rs.next()) {
                    txt_admission_no.setText(rs.getString("admissionno"));
                    txt_full_name.setText(rs.getString("fullname"));
                    txt_name_initials.setText(rs.getString("namewithinitials"));
                    txt_address.setText(rs.getString("address"));
                    dc_birthday.setDate(new SimpleDateFormat("yyyy-MM-dd", Locale.ENGLISH).parse(rs.getString("birthday")));
                    cb_admission_grade.setSelectedItem(rs.getString("admissiongrade"));
                    dc_admission_date.setDate(new SimpleDateFormat("yyyy-MM-dd", Locale.ENGLISH).parse(rs.getString("admissiondate")));
                    txt_nic.setText(rs.getString("nic"));
                    String a[] = rs.getString("class").split("_");
                    cb_grade.setSelectedItem(a[0]);
                    cb_class.setSelectedItem(rs.getString("class"));
                    dc_examyear.setYear(Integer.parseInt(rs.getString("year")));
                    cb_regno.setSelectedItem(rs.getString("regno"));
                    cb_3rd_subject.setSelectedItem(rs.getString("3subject"));
                    txt_ex_curricular.setText(rs.getString("excuricularact"));
                    txt_special_notes.setText(rs.getString("specialnotes"));
                    imageBlob = rs.getBlob("photo");
                    InputStream binaryStream = imageBlob.getBinaryStream(1, imageBlob.length());
                    System.out.println("elakiri");
                    image = ImageIO.read(binaryStream);
                    image = image.getScaledInstance(lbl_photo.getWidth(), lbl_photo.getHeight(), Image.SCALE_SMOOTH);

                }
                lbl_photo.setIcon(new ImageIcon(image));
                ResultSet rs2 = DataBase.executequary1("father", "admissionno", txt_admission_no.getText());
                while (rs2.next()) {
                    txt_fatehes_name.setText(rs2.getString("name"));
                    txt_fathers_occupation.setText(rs2.getString("occupation"));
                    txt_fathers_officeaddress.setText(rs2.getString("officeaddress"));
                    txt_fathers_contactno.setText(rs2.getString("contactno"));
                }
            } else {
                Object[] options = {"Ok"};
                JOptionPane.showOptionDialog(new JFrame(), "Name doesn't exsist plase check spelling and try again", "Student Information System", JOptionPane.OK_OPTION, JOptionPane.ERROR_MESSAGE, null, options, options[0]);
                txt_mothers_name.setText("");


            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void cb_regnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_regnoActionPerformed
        
    }//GEN-LAST:event_cb_regnoActionPerformed

    private void cb_3rd_subjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_3rd_subjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_3rd_subjectActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        try {
            String admit = txt_admission_no.getText();
            
            DataBase.executeupdate("DELETE FROM student where admissionno='" + admit + "'");
            DataBase.executeupdate("DELETE FROM 12_1st_term where admissionno='" + admit + "'");
            DataBase.executeupdate("DELETE FROM 12_2nd_term where admissionno='" + admit + "'");
            DataBase.executeupdate("DELETE FROM 12_3rd_term where admissionno='" + admit + "'");
            DataBase.executeupdate("DELETE FROM 13_1st_term where admissionno='" + admit + "'");
            DataBase.executeupdate("DELETE FROM 13_2nd_term where admissionno='" + admit + "'");
            DataBase.executeupdate("DELETE FROM 13_3rd_term where admissionno='" + admit + "'");
            DataBase.executeupdate("DELETE FROM father where admissionno='" + admit + "'");
            DataBase.executeupdate("DELETE FROM mother where admissionno='" + admit + "'");
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
try {
            if (cb_regno.getSelectedIndex() == -1) {
            } else {

                Setnull();
                Blob imageBlob = null;
                Image image = null;
                ResultSet rs1 = DataBase.executequary3("student", "class", String.valueOf(cb_class.getSelectedItem()), "regno", String.valueOf(cb_regno.getSelectedItem()));
                if (rs1.next()) {
                    ResultSet rs = DataBase.executequary3("student", "class", String.valueOf(cb_class.getSelectedItem()), "regno", String.valueOf(cb_regno.getSelectedItem()));
                    while (rs.next()) {
                        String a[] = rs.getString("class").split("_");
                        cb_grade.setSelectedItem(a[0]);
                        cb_class.setSelectedItem(rs.getString("class"));
                        cb_regno.setSelectedItem(rs.getString("regno"));
                        txt_admission_no.setText(rs.getString("admissionno"));
                        txt_full_name.setText(rs.getString("fullname"));
                        txt_name_initials.setText(rs.getString("namewithinitials"));
                        txt_address.setText(rs.getString("address"));
                        dc_birthday.setDate(new SimpleDateFormat("yyyy-MM-dd", Locale.ENGLISH).parse(rs.getString("birthday")));
                        cb_admission_grade.setSelectedItem(rs.getString("admissiongrade"));
                        dc_admission_date.setDate(new SimpleDateFormat("yyyy-MM-dd", Locale.ENGLISH).parse(rs.getString("admissiondate")));
                        txt_nic.setText(rs.getString("nic"));
                        
                        dc_examyear.setYear(Integer.parseInt(rs.getString("year")));
                        cb_3rd_subject.setSelectedItem(rs.getString("3subject"));
                        txt_ex_curricular.setText(rs.getString("excuricularact"));
                        txt_special_notes.setText(rs.getString("specialnotes"));
                        imageBlob = rs.getBlob("photo");
                        InputStream binaryStream = imageBlob.getBinaryStream(1, imageBlob.length());
                        
                        System.out.println("elakiri");
                        image = ImageIO.read(binaryStream);
                        image = image.getScaledInstance(lbl_photo.getWidth(), lbl_photo.getHeight(), Image.SCALE_SMOOTH);


                    }
                    lbl_photo.setIcon(new ImageIcon(image));
                    ResultSet rs2 = DataBase.executequary1("father", "admissionno", txt_admission_no.getText());
                    while (rs2.next()) {
                        txt_fatehes_name.setText(rs2.getString("name"));
                        txt_fathers_occupation.setText(rs2.getString("occupation"));
                        txt_fathers_officeaddress.setText(rs2.getString("officeaddress"));
                        txt_fathers_contactno.setText(rs2.getString("contactno"));
                    }
                    ResultSet rs3 = DataBase.executequary1("mother", "admissionno", txt_admission_no.getText());
                    while (rs3.next()) {
                        txt_mothers_name.setText(rs3.getString("name"));
                        txt_mothers_occ.setText(rs3.getString("occupation"));
                        txt_mothers_officeadd.setText(rs3.getString("officeaddress"));
                        txt_mothers_contactno.setText(rs3.getString("contactno"));
                    }
                } else {
                    Object[] options = {"Ok"};
                    JOptionPane.showOptionDialog(new JFrame(), "Register No not exsist!", "Student Information System", JOptionPane.OK_OPTION, JOptionPane.ERROR_MESSAGE, null, options, options[0]);
                    cb_regno.setSelectedIndex(-1);
                    cb_grade.setSelectedIndex(-1);
                    cb_class.setSelectedIndex(-1);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }       // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void cb_gradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_gradeActionPerformed
        try {
            Vector v = new Vector();
            ResultSet rs = DataBase.executequary1("class", "grade", (String) cb_grade.getSelectedItem());
            while (rs.next()) {
                v.add(rs.getString("class"));
            }
            cb_class.setModel(new DefaultComboBoxModel(v));
            cb_class.setSelectedIndex(-1);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_cb_gradeActionPerformed

    private void cb_classActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_classActionPerformed
        try {
            if (cb_class.getSelectedIndex() == -1) {
            } else {

                String a = "";
                Vector v = new Vector();
                Vector v1 = new Vector();
                int x = 0;
                ResultSet rs = DataBase.executequary1("class", "class", (String) cb_class.getSelectedItem());
                while (rs.next()) {
                    x = Integer.parseInt(rs.getString("students"));
                    a = rs.getString("subject");
                }
                if (a.equals("Mathematics")) {
                    stsubject = "Mathematics";
                    ndsubject = "Physics";
                    v1.add("Chemistry");
                    v1.add("IT");
                } else {
                    stsubject = "Bio-Science";
                    ndsubject = "Chemistry";
                    v1.add("Physics");
                    v1.add("Agriculture");
                }
                for (int i = 1; i < x + 1; i++) {
                    if (i<10) {
                        v.add("0"+String.valueOf(i));
                    } else {
                        v.add(i);
                    }
                }
                cb_3rd_subject.setModel(new DefaultComboBoxModel(v1));
                cb_regno.setModel(new DefaultComboBoxModel(v));
                cb_regno.setSelectedIndex(-1);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_cb_classActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //  try {
                //UIManager.setLookAndFeel(new SubstanceModerateLookAndFeel());
                new SearchStudent().setVisible(true);
                // } catch (UnsupportedLookAndFeelException ex) {
                //  Logger.getLogger(AddStudent.class.getName()).log(Level.SEVERE, null, ex);
                //   }



            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cb_3rd_subject;
    private javax.swing.JComboBox cb_admission_grade;
    private javax.swing.JComboBox cb_class;
    private javax.swing.JComboBox cb_grade;
    private javax.swing.JComboBox cb_regno;
    private com.toedter.calendar.JDateChooser dc_admission_date;
    private com.toedter.calendar.JDateChooser dc_birthday;
    private com.toedter.calendar.JYearChooser dc_examyear;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_photo;
    private javax.swing.JTextPane txt_address;
    private javax.swing.JTextField txt_admission_no;
    private javax.swing.JTextPane txt_ex_curricular;
    private javax.swing.JTextField txt_fatehes_name;
    private javax.swing.JTextField txt_fathers_contactno;
    private javax.swing.JTextField txt_fathers_occupation;
    private javax.swing.JTextPane txt_fathers_officeaddress;
    private javax.swing.JTextField txt_full_name;
    private javax.swing.JTextField txt_mothers_contactno;
    private javax.swing.JTextField txt_mothers_name;
    private javax.swing.JTextField txt_mothers_occ;
    private javax.swing.JTextPane txt_mothers_officeadd;
    private javax.swing.JTextField txt_name_initials;
    private javax.swing.JTextField txt_nic;
    private javax.swing.JTextPane txt_special_notes;
    private javax.swing.JTextField txtpath;
    // End of variables declaration//GEN-END:variables

    public static String getBackUpPath() {

        String backUpPath = "";
        JFileChooser fc = null;
        if (fc == null) {
            fc = new JFileChooser();
            fc.setFileSelectionMode(JFileChooser.FILES_ONLY);

            fc.setAcceptAllFileFilterUsed(true);
            ImagePriview preview = new ImagePriview();
            fc.setAccessory(preview);
            fc.addPropertyChangeListener(preview);

        }
        int returnVal = fc.showDialog(null, "Open");
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();

            backUpPath = file.getAbsolutePath();

        }
        return backUpPath;

    }

    public void Setnull() {
        txt_full_name.setText("");
        
        txt_address.setText("");
        dc_birthday.setDate(null);
        cb_admission_grade.setSelectedIndex(0);
        dc_admission_date.setDate(null);
        txt_nic.setText("");

        dc_examyear.setYear(0);

        cb_3rd_subject.setSelectedIndex(0);
        txt_ex_curricular.setText("");
        txt_special_notes.setText("");
        lbl_photo.setIcon(null);

        txt_fathers_occupation.setText("");
        txt_fathers_officeaddress.setText("");
        txt_fathers_contactno.setText("");

        txt_mothers_occ.setText("");
        txt_mothers_officeadd.setText("");
        txt_mothers_contactno.setText("");


    }
}
